// StripWolf - an open source comic book reader
// Copyright (C) 2026 Dapplo - Robin Krom
//
// For more information see: https://github.com/dapplo/StripWolf
// The StripWolf project is hosted on GitHub https://github.com/dapplo/StripWolf
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.IO.Compression;
using System.Security.Cryptography;

namespace StripWolf.Core.Tests;

/// <summary>
/// Access to the synthetic fixtures in TestData (generated by TestData/generate_fixtures.py).
/// </summary>
internal static class TestFiles
{
    public const string CbzWithComicInfo = "comic_with_info.cbz";
    public const string CbzWithoutComicInfo = "comic_no_info.cbz";
    public const string CbzWithSubfolders = "comic_subfolders.cbz";
    public const string Cbt = "comic.cbt";
    public const string Cb7 = "comic.cb7";
    public const string Cb7Solid = "comic_solid.cb7";
    public const string Cbr = "comic.cbr";
    public const string CbrSolid = "comic_solid.cbr";
    public const string Pdf = "comic.pdf";
    public const string Epub = "comic.epub";

    public const string ComicInfoTitle = "The Wolf Strip";
    public const string ComicInfoSeries = "StripWolf Test Series";
    public const string EpubTitle = "The Wolf Strip (EPUB)";
    public const string EpubAuthor = "Alice Writer";
    public const string EpubDescription = "A fixed layout test EPUB.";

    /// <summary>
    /// All archive fixtures containing the four standard pages (+ junk entries which must be ignored)
    /// </summary>
    public static readonly string[] StandardArchives = [CbzWithComicInfo, CbzWithoutComicInfo, Cbt, Cb7, Cb7Solid, Cbr, CbrSolid];

    /// <summary>
    /// The archive fixtures which also contain a ComicInfo.xml
    /// </summary>
    public static readonly string[] ArchivesWithComicInfo = [CbzWithComicInfo, Cbt, Cb7, Cb7Solid, Cbr, CbrSolid];

    /// <summary>
    /// The page names in natural order (the archives store them in a different physical order)
    /// </summary>
    public static readonly string[] ExpectedPageNames = ["page1.jpg", "page2.png", "page3-4.jpg", "page10.jpg"];

    /// <summary>
    /// Page names of comic_subfolders.cbz in natural order and the page they contain
    /// </summary>
    public static readonly (string Name, string Page)[] SubfolderPages =
    [
        ("ch2/p1.jpg", "page1.jpg"),
        ("ch2/p2.png", "page2.png"),
        ("ch2/p10.jpg", "page3-4.jpg"),
        ("ch10/p1.jpg", "page10.jpg")
    ];

    /// <summary>
    /// The pages the fake PDF renderer returns (all JPEG, like the real PDFium renderer)
    /// </summary>
    public static readonly string[] FakePdfPages = ["page1.jpg", "page3-4.jpg", "page10.jpg"];

    public static string DirectoryPath => Path.Combine(AppContext.BaseDirectory, "TestData");

    public static string Get(string fixtureName)
    {
        var path = Path.Combine(DirectoryPath, fixtureName);
        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"Test fixture '{fixtureName}' is missing, run TestData/generate_fixtures.py", path);
        }

        return path;
    }

    public static byte[] PageBytes(string pageName)
    {
        return File.ReadAllBytes(Path.Combine(DirectoryPath, "pages", pageName));
    }

    public static List<byte[]> FakePdfPageBytes()
    {
        return FakePdfPages.Select(PageBytes).ToList();
    }

    public static string Sha256(byte[] data)
    {
        return Convert.ToHexString(SHA256.HashData(data));
    }

    /// <summary>
    /// Names of all entries of a ZIP/CBZ file
    /// </summary>
    public static List<string> ZipEntryNames(string zipPath)
    {
        using var archive = ZipFile.OpenRead(zipPath);
        return archive.Entries.Select(entry => entry.FullName).ToList();
    }

    public static byte[] ReadZipEntry(string zipPath, string entryName)
    {
        using var archive = ZipFile.OpenRead(zipPath);
        var entry = archive.GetEntry(entryName) ?? throw new InvalidOperationException($"No entry '{entryName}' in {zipPath}");
        using var entryStream = entry.Open();
        using var memoryStream = new MemoryStream();
        entryStream.CopyTo(memoryStream);
        return memoryStream.ToArray();
    }

    /// <summary>
    /// Creates a CBZ with the supplied entries (name, content)
    /// </summary>
    public static void CreateZip(string path, params (string Name, byte[] Content)[] entries)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        using var archive = ZipFile.Open(path, ZipArchiveMode.Create);
        foreach (var (name, content) in entries)
        {
            var entry = archive.CreateEntry(name);
            using var entryStream = entry.Open();
            entryStream.Write(content, 0, content.Length);
        }
    }

    public static byte[] ReadAll(Stream stream)
    {
        if (stream.CanSeek)
        {
            stream.Position = 0;
        }

        using var memoryStream = new MemoryStream();
        stream.CopyTo(memoryStream);
        return memoryStream.ToArray();
    }
}
