// StripWolf - an open source comic book reader
// Copyright (C) 2026 Dapplo - Robin Krom
//
// For more information see: https://github.com/dapplo/StripWolf
// The StripWolf project is hosted on GitHub https://github.com/dapplo/StripWolf
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Text.Json;
using SQLite;
using CommunityToolkit.Mvvm.ComponentModel;
using StripWolf.Core.Data;
using System.Diagnostics.CodeAnalysis;

namespace StripWolf.Core.Models;

/// <summary>
/// Represents a custom HTTP header
/// </summary>
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.NonPublicFields)]
public partial class KomgaHeader : ObservableObject
{
    // Note: explicit properties instead of [ObservableProperty]: the System.Text.Json source generator can't see
    // properties generated by another source generator, so Name/Value were never written to settings.json
    // (custom headers were saved as {} and lost on restart).
    private string _name = string.Empty;
    private string _value = string.Empty;

    public string Name
    {
        get => _name;
        set => SetProperty(ref _name, value);
    }

    public string Value
    {
        get => _value;
        set => SetProperty(ref _value, value);
    }
}

/// <summary>
/// Represents a Komga server connection configuration
/// </summary>
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.NonPublicFields)]
public class KomgaServer
{
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }

    /// <summary>
    /// Display name for the server
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Base URL of the Komga server (e.g., https://komga.example.com)
    /// </summary>
    public string BaseUrl { get; set; } = string.Empty;

    /// <summary>
    /// Username for authentication
    /// </summary>
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// Password for authentication (should be stored securely)
    /// </summary>
    public string Password { get; set; } = string.Empty;

    /// <summary>
    /// API Key for authentication (preferred over username/password)
    /// </summary>
    public string ApiKey { get; set; } = string.Empty;

    /// <summary>
    /// Custom HTTP headers to be sent with every request
    /// </summary>
    [Ignore]
    public List<KomgaHeader> CustomHeaders { get; set; } = [];

    // Note: CustomHeadersJson (a copy of the headers for the SQLite table) was removed together with the table,
    // servers are only stored in settings.json.

    /// <summary>
    /// Last successful connection time
    /// </summary>
    public DateTime? LastConnected { get; set; }

    /// <summary>
    /// Gets or sets whether to bypass SSL/TLS certificate verification.
    /// </summary>
    public bool BypassSslValidation { get; set; }

    public override bool Equals(object? obj)
    {
        if (obj is not KomgaServer other)
        {
            return false;
        }

        if (Id != 0 && other.Id != 0)
        {
            return Id == other.Id;
        }

        return string.Equals(BaseUrl, other.BaseUrl, StringComparison.OrdinalIgnoreCase) &&
               string.Equals(Username, other.Username, StringComparison.Ordinal);
    }

    public override int GetHashCode()
    {
        if (Id != 0)
        {
            return Id.GetHashCode();
        }

        return HashCode.Combine(
            BaseUrl?.ToLowerInvariant() ?? string.Empty,
            Username ?? string.Empty);
    }
}

